# Generated by Django 5.2 on 2026-03-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesquotationline',
            name='subtotal',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
