# Generated by Django 5.2 on 2026-03-13 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('sales', '0003_salesquotationline_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='salesquotation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.contact'),
        ),
    ]
