# Generated by Django 5.2 on 2026-03-06 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_permission_role_rolepermission_usercompanyrole'),
        ('finance', '0005_vendor'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bill_number', models.CharField(max_length=50)),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=4, max_digits=20)),
                ('amount_paid', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.company')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='finance.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
