# Generated by Django 5.2 on 2026-03-13 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('finance', '0010_customerinvoiceline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='account_receivable',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_invoices', to='contacts.contact'),
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='account_payable',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='company',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bills', to='contacts.contact'),
        ),
    ]
