# Generated by Django 5.2 on 2026-03-13 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_remove_customer_account_receivable_and_more'),
        ('purchases', '0002_alter_purchaseorder_vendor'),
        ('sales', '0004_alter_salesorder_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
