# Generated by Django 5.2 on 2026-03-16 17:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_delete_customer_delete_vendor'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorbill',
            options={'ordering': ['-bill_date']},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('vendor_bill', 'Vendor Bill'), ('customer_invoice', 'Customer Invoice'), ('po_receipt', 'PO Receipt'), ('payment', 'Payment')], default='manual', max_length=30),
        ),
        migrations.CreateModel(
            name='JournalEntryAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('change_type', models.CharField(choices=[('line_added', 'Line Added'), ('line_modified', 'Line Modified'), ('line_deleted', 'Line Deleted'), ('account_changed', 'Account Changed'), ('amount_changed', 'Amount Changed'), ('posted', 'Posted'), ('unposted', 'Unposted')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='finance.journalentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
