# Generated by Django 5.2 on 2026-03-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmove_stockquant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='can_be_purchased',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='can_be_sold',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='digital_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('storable', 'Storable Product'), ('consumable', 'Consumable'), ('service', 'Service'), ('digital', 'Digital Product')], default='storable', max_length=20),
        ),
    ]
